### ISSUE TITLE
Worshops and events shows an %amp in chrom

### ISSUE THREAD

**Issue by hiddendragonXVII** [nuevomundo/pnm-comingsoon#1]
http://projectnuevomundo.com/blog/category/workshops-events/
![image](https://cloud.githubusercontent.com/assets/241176/7454216/ff6f1eca-f247-11e4-8cf8-42582c61078d.png)

**Comment by davidacasey** [comment]
Hey Paul, 
 I don¹t really understand this email?

David Casey
Founder & Network Architect
www.ProjectNuevoMundo.org http://www.projectnuevomundo.org/

Spread the word on Facebook!
https://www.facebook.com/ProjectNuevoMundo

Follow us on Twitter!
https://twitter.com/PrjctNuevoMundo

From:  Paul Wand notifications@github.com
Reply-To:  nuevomundo/pnm-comingsoon
<reply+009995a7af2aead99bf1d304f6f6cfa06d9888091966671392cf00000001115f35c89
2a169ce045a2e66@reply.github.com>
Date:  Monday, May 4, 2015 at 6:27 AM
To:  nuevomundo/pnm-comingsoon pnm-comingsoon@noreply.github.com
Subject:  [pnm-comingsoon] Worshops and events shows an %amp in chrom (#1)

http://projectnuevomundo.com/blog/category/workshops-events/
 <https://cloud.githubusercontent.com/assets/241176/7454216/ff6f1eca-f247-11
e4-8cf8-42582c61078d.png>


Reply to this email directly or view it on GitHub
https://github.com/nuevomundo/pnm-comingsoon/issues/1 .

**Comment by hiddendragonXVII** [comment]
David,

I believe that was a result of the issue I added to github,

there was a typo and I posted it there, since you’re a watcher on the repo, you were notified.

I believe Lucas already sniped it.

Its been really fun working on this project so far, I’m stoked for when you come out here :

Cosmic Wishes,

~Paul N Wand

**Comment by davidacasey** [comment]
Awesome! Ok, I figured it was data-related!
You guys will have to show me the way around github when I get there in a
couple weeks! Can¹t wait :)
Keep rockin¹ it!

David Casey
Founder & Network Architect
www.ProjectNuevoMundo.org http://www.projectnuevomundo.org/

Spread the word on Facebook!
https://www.facebook.com/ProjectNuevoMundo

Follow us on Twitter!
https://twitter.com/PrjctNuevoMundo

From:  Lukas notifications@github.com
Reply-To:  nuevomundo/pnm-comingsoon
<reply+009995a76a3f875846653f64662181f4a9e2cabd5a03eab492cf00000001116082bc9
2a169ce045a2e66@reply.github.com>
Date:  Tuesday, May 5, 2015 at 6:08 AM
To:  nuevomundo/pnm-comingsoon pnm-comingsoon@noreply.github.com
Cc:  Mac david@projectnuevomundo.org
Subject:  Re: [pnm-comingsoon] Worshops and events shows an %amp in chrom
(#1)

Closed #1 https://github.com/nuevomundo/pnm-comingsoon/issues/1 .


Reply to this email directly or view it on GitHub
https://github.com/nuevomundo/pnm-comingsoon/issues/1#event-297197886 .
